// Code generated by ent, DO NOT EDIT.

package todo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/utibori-jp/yojitsu-tracker/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldDescription, v))
}

// EstimatedTimeSec applies equality check predicate on the "estimated_time_sec" field. It's identical to EstimatedTimeSecEQ.
func EstimatedTimeSec(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldEstimatedTimeSec, v))
}

// ActualTimeSec applies equality check predicate on the "actual_time_sec" field. It's identical to ActualTimeSecEQ.
func ActualTimeSec(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldActualTimeSec, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldDueDate, v))
}

// ReflectionMemo applies equality check predicate on the "reflection_memo" field. It's identical to ReflectionMemoEQ.
func ReflectionMemo(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldReflectionMemo, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Todo {
	return predicate.Todo(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Todo {
	return predicate.Todo(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Todo {
	return predicate.Todo(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Todo {
	return predicate.Todo(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Todo {
	return predicate.Todo(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Todo {
	return predicate.Todo(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Todo {
	return predicate.Todo(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Todo {
	return predicate.Todo(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Todo {
	return predicate.Todo(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Todo {
	return predicate.Todo(sql.FieldContainsFold(FieldDescription, v))
}

// EstimatedTimeSecEQ applies the EQ predicate on the "estimated_time_sec" field.
func EstimatedTimeSecEQ(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldEstimatedTimeSec, v))
}

// EstimatedTimeSecNEQ applies the NEQ predicate on the "estimated_time_sec" field.
func EstimatedTimeSecNEQ(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldEstimatedTimeSec, v))
}

// EstimatedTimeSecIn applies the In predicate on the "estimated_time_sec" field.
func EstimatedTimeSecIn(vs ...int32) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldEstimatedTimeSec, vs...))
}

// EstimatedTimeSecNotIn applies the NotIn predicate on the "estimated_time_sec" field.
func EstimatedTimeSecNotIn(vs ...int32) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldEstimatedTimeSec, vs...))
}

// EstimatedTimeSecGT applies the GT predicate on the "estimated_time_sec" field.
func EstimatedTimeSecGT(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldEstimatedTimeSec, v))
}

// EstimatedTimeSecGTE applies the GTE predicate on the "estimated_time_sec" field.
func EstimatedTimeSecGTE(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldEstimatedTimeSec, v))
}

// EstimatedTimeSecLT applies the LT predicate on the "estimated_time_sec" field.
func EstimatedTimeSecLT(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldEstimatedTimeSec, v))
}

// EstimatedTimeSecLTE applies the LTE predicate on the "estimated_time_sec" field.
func EstimatedTimeSecLTE(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldEstimatedTimeSec, v))
}

// ActualTimeSecEQ applies the EQ predicate on the "actual_time_sec" field.
func ActualTimeSecEQ(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldActualTimeSec, v))
}

// ActualTimeSecNEQ applies the NEQ predicate on the "actual_time_sec" field.
func ActualTimeSecNEQ(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldActualTimeSec, v))
}

// ActualTimeSecIn applies the In predicate on the "actual_time_sec" field.
func ActualTimeSecIn(vs ...int32) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldActualTimeSec, vs...))
}

// ActualTimeSecNotIn applies the NotIn predicate on the "actual_time_sec" field.
func ActualTimeSecNotIn(vs ...int32) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldActualTimeSec, vs...))
}

// ActualTimeSecGT applies the GT predicate on the "actual_time_sec" field.
func ActualTimeSecGT(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldActualTimeSec, v))
}

// ActualTimeSecGTE applies the GTE predicate on the "actual_time_sec" field.
func ActualTimeSecGTE(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldActualTimeSec, v))
}

// ActualTimeSecLT applies the LT predicate on the "actual_time_sec" field.
func ActualTimeSecLT(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldActualTimeSec, v))
}

// ActualTimeSecLTE applies the LTE predicate on the "actual_time_sec" field.
func ActualTimeSecLTE(v int32) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldActualTimeSec, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldDueDate, v))
}

// DueDateIsNil applies the IsNil predicate on the "due_date" field.
func DueDateIsNil() predicate.Todo {
	return predicate.Todo(sql.FieldIsNull(FieldDueDate))
}

// DueDateNotNil applies the NotNil predicate on the "due_date" field.
func DueDateNotNil() predicate.Todo {
	return predicate.Todo(sql.FieldNotNull(FieldDueDate))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v Priority) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v Priority) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...Priority) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...Priority) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldPriority, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldStatus, vs...))
}

// ReflectionMemoEQ applies the EQ predicate on the "reflection_memo" field.
func ReflectionMemoEQ(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEQ(FieldReflectionMemo, v))
}

// ReflectionMemoNEQ applies the NEQ predicate on the "reflection_memo" field.
func ReflectionMemoNEQ(v string) predicate.Todo {
	return predicate.Todo(sql.FieldNEQ(FieldReflectionMemo, v))
}

// ReflectionMemoIn applies the In predicate on the "reflection_memo" field.
func ReflectionMemoIn(vs ...string) predicate.Todo {
	return predicate.Todo(sql.FieldIn(FieldReflectionMemo, vs...))
}

// ReflectionMemoNotIn applies the NotIn predicate on the "reflection_memo" field.
func ReflectionMemoNotIn(vs ...string) predicate.Todo {
	return predicate.Todo(sql.FieldNotIn(FieldReflectionMemo, vs...))
}

// ReflectionMemoGT applies the GT predicate on the "reflection_memo" field.
func ReflectionMemoGT(v string) predicate.Todo {
	return predicate.Todo(sql.FieldGT(FieldReflectionMemo, v))
}

// ReflectionMemoGTE applies the GTE predicate on the "reflection_memo" field.
func ReflectionMemoGTE(v string) predicate.Todo {
	return predicate.Todo(sql.FieldGTE(FieldReflectionMemo, v))
}

// ReflectionMemoLT applies the LT predicate on the "reflection_memo" field.
func ReflectionMemoLT(v string) predicate.Todo {
	return predicate.Todo(sql.FieldLT(FieldReflectionMemo, v))
}

// ReflectionMemoLTE applies the LTE predicate on the "reflection_memo" field.
func ReflectionMemoLTE(v string) predicate.Todo {
	return predicate.Todo(sql.FieldLTE(FieldReflectionMemo, v))
}

// ReflectionMemoContains applies the Contains predicate on the "reflection_memo" field.
func ReflectionMemoContains(v string) predicate.Todo {
	return predicate.Todo(sql.FieldContains(FieldReflectionMemo, v))
}

// ReflectionMemoHasPrefix applies the HasPrefix predicate on the "reflection_memo" field.
func ReflectionMemoHasPrefix(v string) predicate.Todo {
	return predicate.Todo(sql.FieldHasPrefix(FieldReflectionMemo, v))
}

// ReflectionMemoHasSuffix applies the HasSuffix predicate on the "reflection_memo" field.
func ReflectionMemoHasSuffix(v string) predicate.Todo {
	return predicate.Todo(sql.FieldHasSuffix(FieldReflectionMemo, v))
}

// ReflectionMemoIsNil applies the IsNil predicate on the "reflection_memo" field.
func ReflectionMemoIsNil() predicate.Todo {
	return predicate.Todo(sql.FieldIsNull(FieldReflectionMemo))
}

// ReflectionMemoNotNil applies the NotNil predicate on the "reflection_memo" field.
func ReflectionMemoNotNil() predicate.Todo {
	return predicate.Todo(sql.FieldNotNull(FieldReflectionMemo))
}

// ReflectionMemoEqualFold applies the EqualFold predicate on the "reflection_memo" field.
func ReflectionMemoEqualFold(v string) predicate.Todo {
	return predicate.Todo(sql.FieldEqualFold(FieldReflectionMemo, v))
}

// ReflectionMemoContainsFold applies the ContainsFold predicate on the "reflection_memo" field.
func ReflectionMemoContainsFold(v string) predicate.Todo {
	return predicate.Todo(sql.FieldContainsFold(FieldReflectionMemo, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Todo {
	return predicate.Todo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Todo {
	return predicate.Todo(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Todo) predicate.Todo {
	return predicate.Todo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Todo) predicate.Todo {
	return predicate.Todo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Todo) predicate.Todo {
	return predicate.Todo(sql.NotPredicates(p))
}
