// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/utibori-jp/yojitsu-tracker/ent/predicate"
	"github.com/utibori-jp/yojitsu-tracker/ent/todo"
	"github.com/utibori-jp/yojitsu-tracker/ent/user"
)

// TodoUpdate is the builder for updating Todo entities.
type TodoUpdate struct {
	config
	hooks    []Hook
	mutation *TodoMutation
}

// Where appends a list predicates to the TodoUpdate builder.
func (tu *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TodoUpdate) SetUpdatedAt(t time.Time) *TodoUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetName sets the "name" field.
func (tu *TodoUpdate) SetName(s string) *TodoUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableName(s *string) *TodoUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetDescription sets the "description" field.
func (tu *TodoUpdate) SetDescription(s string) *TodoUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableDescription(s *string) *TodoUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *TodoUpdate) ClearDescription() *TodoUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetEstimatedTimeSec sets the "estimated_time_sec" field.
func (tu *TodoUpdate) SetEstimatedTimeSec(i int32) *TodoUpdate {
	tu.mutation.ResetEstimatedTimeSec()
	tu.mutation.SetEstimatedTimeSec(i)
	return tu
}

// SetNillableEstimatedTimeSec sets the "estimated_time_sec" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableEstimatedTimeSec(i *int32) *TodoUpdate {
	if i != nil {
		tu.SetEstimatedTimeSec(*i)
	}
	return tu
}

// AddEstimatedTimeSec adds i to the "estimated_time_sec" field.
func (tu *TodoUpdate) AddEstimatedTimeSec(i int32) *TodoUpdate {
	tu.mutation.AddEstimatedTimeSec(i)
	return tu
}

// SetActualTimeSec sets the "actual_time_sec" field.
func (tu *TodoUpdate) SetActualTimeSec(i int32) *TodoUpdate {
	tu.mutation.ResetActualTimeSec()
	tu.mutation.SetActualTimeSec(i)
	return tu
}

// SetNillableActualTimeSec sets the "actual_time_sec" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableActualTimeSec(i *int32) *TodoUpdate {
	if i != nil {
		tu.SetActualTimeSec(*i)
	}
	return tu
}

// AddActualTimeSec adds i to the "actual_time_sec" field.
func (tu *TodoUpdate) AddActualTimeSec(i int32) *TodoUpdate {
	tu.mutation.AddActualTimeSec(i)
	return tu
}

// SetDueDate sets the "due_date" field.
func (tu *TodoUpdate) SetDueDate(t time.Time) *TodoUpdate {
	tu.mutation.SetDueDate(t)
	return tu
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableDueDate(t *time.Time) *TodoUpdate {
	if t != nil {
		tu.SetDueDate(*t)
	}
	return tu
}

// ClearDueDate clears the value of the "due_date" field.
func (tu *TodoUpdate) ClearDueDate() *TodoUpdate {
	tu.mutation.ClearDueDate()
	return tu
}

// SetPriority sets the "priority" field.
func (tu *TodoUpdate) SetPriority(t todo.Priority) *TodoUpdate {
	tu.mutation.SetPriority(t)
	return tu
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (tu *TodoUpdate) SetNillablePriority(t *todo.Priority) *TodoUpdate {
	if t != nil {
		tu.SetPriority(*t)
	}
	return tu
}

// SetStatus sets the "status" field.
func (tu *TodoUpdate) SetStatus(t todo.Status) *TodoUpdate {
	tu.mutation.SetStatus(t)
	return tu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableStatus(t *todo.Status) *TodoUpdate {
	if t != nil {
		tu.SetStatus(*t)
	}
	return tu
}

// SetReflectionMemo sets the "reflection_memo" field.
func (tu *TodoUpdate) SetReflectionMemo(s string) *TodoUpdate {
	tu.mutation.SetReflectionMemo(s)
	return tu
}

// SetNillableReflectionMemo sets the "reflection_memo" field if the given value is not nil.
func (tu *TodoUpdate) SetNillableReflectionMemo(s *string) *TodoUpdate {
	if s != nil {
		tu.SetReflectionMemo(*s)
	}
	return tu
}

// ClearReflectionMemo clears the value of the "reflection_memo" field.
func (tu *TodoUpdate) ClearReflectionMemo() *TodoUpdate {
	tu.mutation.ClearReflectionMemo()
	return tu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (tu *TodoUpdate) SetOwnerID(id int) *TodoUpdate {
	tu.mutation.SetOwnerID(id)
	return tu
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (tu *TodoUpdate) SetNillableOwnerID(id *int) *TodoUpdate {
	if id != nil {
		tu = tu.SetOwnerID(*id)
	}
	return tu
}

// SetOwner sets the "owner" edge to the User entity.
func (tu *TodoUpdate) SetOwner(u *User) *TodoUpdate {
	return tu.SetOwnerID(u.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (tu *TodoUpdate) Mutation() *TodoMutation {
	return tu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (tu *TodoUpdate) ClearOwner() *TodoUpdate {
	tu.mutation.ClearOwner()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TodoUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TodoUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TodoUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TodoUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := todo.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TodoUpdate) check() error {
	if v, ok := tu.mutation.Name(); ok {
		if err := todo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Todo.name": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Description(); ok {
		if err := todo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Todo.description": %w`, err)}
		}
	}
	if v, ok := tu.mutation.EstimatedTimeSec(); ok {
		if err := todo.EstimatedTimeSecValidator(v); err != nil {
			return &ValidationError{Name: "estimated_time_sec", err: fmt.Errorf(`ent: validator failed for field "Todo.estimated_time_sec": %w`, err)}
		}
	}
	if v, ok := tu.mutation.ActualTimeSec(); ok {
		if err := todo.ActualTimeSecValidator(v); err != nil {
			return &ValidationError{Name: "actual_time_sec", err: fmt.Errorf(`ent: validator failed for field "Todo.actual_time_sec": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Priority(); ok {
		if err := todo.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Todo.priority": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	if v, ok := tu.mutation.ReflectionMemo(); ok {
		if err := todo.ReflectionMemoValidator(v); err != nil {
			return &ValidationError{Name: "reflection_memo", err: fmt.Errorf(`ent: validator failed for field "Todo.reflection_memo": %w`, err)}
		}
	}
	return nil
}

func (tu *TodoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(todo.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(todo.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(todo.FieldDescription, field.TypeString)
	}
	if value, ok := tu.mutation.EstimatedTimeSec(); ok {
		_spec.SetField(todo.FieldEstimatedTimeSec, field.TypeInt32, value)
	}
	if value, ok := tu.mutation.AddedEstimatedTimeSec(); ok {
		_spec.AddField(todo.FieldEstimatedTimeSec, field.TypeInt32, value)
	}
	if value, ok := tu.mutation.ActualTimeSec(); ok {
		_spec.SetField(todo.FieldActualTimeSec, field.TypeInt32, value)
	}
	if value, ok := tu.mutation.AddedActualTimeSec(); ok {
		_spec.AddField(todo.FieldActualTimeSec, field.TypeInt32, value)
	}
	if value, ok := tu.mutation.DueDate(); ok {
		_spec.SetField(todo.FieldDueDate, field.TypeTime, value)
	}
	if tu.mutation.DueDateCleared() {
		_spec.ClearField(todo.FieldDueDate, field.TypeTime)
	}
	if value, ok := tu.mutation.Priority(); ok {
		_spec.SetField(todo.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(todo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.ReflectionMemo(); ok {
		_spec.SetField(todo.FieldReflectionMemo, field.TypeString, value)
	}
	if tu.mutation.ReflectionMemoCleared() {
		_spec.ClearField(todo.FieldReflectionMemo, field.TypeString)
	}
	if tu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.OwnerTable,
			Columns: []string{todo.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.OwnerTable,
			Columns: []string{todo.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TodoUpdateOne is the builder for updating a single Todo entity.
type TodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TodoUpdateOne) SetUpdatedAt(t time.Time) *TodoUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetName sets the "name" field.
func (tuo *TodoUpdateOne) SetName(s string) *TodoUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableName(s *string) *TodoUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *TodoUpdateOne) SetDescription(s string) *TodoUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableDescription(s *string) *TodoUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *TodoUpdateOne) ClearDescription() *TodoUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetEstimatedTimeSec sets the "estimated_time_sec" field.
func (tuo *TodoUpdateOne) SetEstimatedTimeSec(i int32) *TodoUpdateOne {
	tuo.mutation.ResetEstimatedTimeSec()
	tuo.mutation.SetEstimatedTimeSec(i)
	return tuo
}

// SetNillableEstimatedTimeSec sets the "estimated_time_sec" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableEstimatedTimeSec(i *int32) *TodoUpdateOne {
	if i != nil {
		tuo.SetEstimatedTimeSec(*i)
	}
	return tuo
}

// AddEstimatedTimeSec adds i to the "estimated_time_sec" field.
func (tuo *TodoUpdateOne) AddEstimatedTimeSec(i int32) *TodoUpdateOne {
	tuo.mutation.AddEstimatedTimeSec(i)
	return tuo
}

// SetActualTimeSec sets the "actual_time_sec" field.
func (tuo *TodoUpdateOne) SetActualTimeSec(i int32) *TodoUpdateOne {
	tuo.mutation.ResetActualTimeSec()
	tuo.mutation.SetActualTimeSec(i)
	return tuo
}

// SetNillableActualTimeSec sets the "actual_time_sec" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableActualTimeSec(i *int32) *TodoUpdateOne {
	if i != nil {
		tuo.SetActualTimeSec(*i)
	}
	return tuo
}

// AddActualTimeSec adds i to the "actual_time_sec" field.
func (tuo *TodoUpdateOne) AddActualTimeSec(i int32) *TodoUpdateOne {
	tuo.mutation.AddActualTimeSec(i)
	return tuo
}

// SetDueDate sets the "due_date" field.
func (tuo *TodoUpdateOne) SetDueDate(t time.Time) *TodoUpdateOne {
	tuo.mutation.SetDueDate(t)
	return tuo
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableDueDate(t *time.Time) *TodoUpdateOne {
	if t != nil {
		tuo.SetDueDate(*t)
	}
	return tuo
}

// ClearDueDate clears the value of the "due_date" field.
func (tuo *TodoUpdateOne) ClearDueDate() *TodoUpdateOne {
	tuo.mutation.ClearDueDate()
	return tuo
}

// SetPriority sets the "priority" field.
func (tuo *TodoUpdateOne) SetPriority(t todo.Priority) *TodoUpdateOne {
	tuo.mutation.SetPriority(t)
	return tuo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillablePriority(t *todo.Priority) *TodoUpdateOne {
	if t != nil {
		tuo.SetPriority(*t)
	}
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *TodoUpdateOne) SetStatus(t todo.Status) *TodoUpdateOne {
	tuo.mutation.SetStatus(t)
	return tuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableStatus(t *todo.Status) *TodoUpdateOne {
	if t != nil {
		tuo.SetStatus(*t)
	}
	return tuo
}

// SetReflectionMemo sets the "reflection_memo" field.
func (tuo *TodoUpdateOne) SetReflectionMemo(s string) *TodoUpdateOne {
	tuo.mutation.SetReflectionMemo(s)
	return tuo
}

// SetNillableReflectionMemo sets the "reflection_memo" field if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableReflectionMemo(s *string) *TodoUpdateOne {
	if s != nil {
		tuo.SetReflectionMemo(*s)
	}
	return tuo
}

// ClearReflectionMemo clears the value of the "reflection_memo" field.
func (tuo *TodoUpdateOne) ClearReflectionMemo() *TodoUpdateOne {
	tuo.mutation.ClearReflectionMemo()
	return tuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (tuo *TodoUpdateOne) SetOwnerID(id int) *TodoUpdateOne {
	tuo.mutation.SetOwnerID(id)
	return tuo
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (tuo *TodoUpdateOne) SetNillableOwnerID(id *int) *TodoUpdateOne {
	if id != nil {
		tuo = tuo.SetOwnerID(*id)
	}
	return tuo
}

// SetOwner sets the "owner" edge to the User entity.
func (tuo *TodoUpdateOne) SetOwner(u *User) *TodoUpdateOne {
	return tuo.SetOwnerID(u.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (tuo *TodoUpdateOne) Mutation() *TodoMutation {
	return tuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (tuo *TodoUpdateOne) ClearOwner() *TodoUpdateOne {
	tuo.mutation.ClearOwner()
	return tuo
}

// Where appends a list predicates to the TodoUpdate builder.
func (tuo *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Todo entity.
func (tuo *TodoUpdateOne) Save(ctx context.Context) (*Todo, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TodoUpdateOne) SaveX(ctx context.Context) *Todo {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TodoUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := todo.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TodoUpdateOne) check() error {
	if v, ok := tuo.mutation.Name(); ok {
		if err := todo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Todo.name": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Description(); ok {
		if err := todo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Todo.description": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.EstimatedTimeSec(); ok {
		if err := todo.EstimatedTimeSecValidator(v); err != nil {
			return &ValidationError{Name: "estimated_time_sec", err: fmt.Errorf(`ent: validator failed for field "Todo.estimated_time_sec": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.ActualTimeSec(); ok {
		if err := todo.ActualTimeSecValidator(v); err != nil {
			return &ValidationError{Name: "actual_time_sec", err: fmt.Errorf(`ent: validator failed for field "Todo.actual_time_sec": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Priority(); ok {
		if err := todo.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Todo.priority": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.ReflectionMemo(); ok {
		if err := todo.ReflectionMemoValidator(v); err != nil {
			return &ValidationError{Name: "reflection_memo", err: fmt.Errorf(`ent: validator failed for field "Todo.reflection_memo": %w`, err)}
		}
	}
	return nil
}

func (tuo *TodoUpdateOne) sqlSave(ctx context.Context) (_node *Todo, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Todo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for _, f := range fields {
			if !todo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(todo.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(todo.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(todo.FieldDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.EstimatedTimeSec(); ok {
		_spec.SetField(todo.FieldEstimatedTimeSec, field.TypeInt32, value)
	}
	if value, ok := tuo.mutation.AddedEstimatedTimeSec(); ok {
		_spec.AddField(todo.FieldEstimatedTimeSec, field.TypeInt32, value)
	}
	if value, ok := tuo.mutation.ActualTimeSec(); ok {
		_spec.SetField(todo.FieldActualTimeSec, field.TypeInt32, value)
	}
	if value, ok := tuo.mutation.AddedActualTimeSec(); ok {
		_spec.AddField(todo.FieldActualTimeSec, field.TypeInt32, value)
	}
	if value, ok := tuo.mutation.DueDate(); ok {
		_spec.SetField(todo.FieldDueDate, field.TypeTime, value)
	}
	if tuo.mutation.DueDateCleared() {
		_spec.ClearField(todo.FieldDueDate, field.TypeTime)
	}
	if value, ok := tuo.mutation.Priority(); ok {
		_spec.SetField(todo.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(todo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.ReflectionMemo(); ok {
		_spec.SetField(todo.FieldReflectionMemo, field.TypeString, value)
	}
	if tuo.mutation.ReflectionMemoCleared() {
		_spec.ClearField(todo.FieldReflectionMemo, field.TypeString)
	}
	if tuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.OwnerTable,
			Columns: []string{todo.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todo.OwnerTable,
			Columns: []string{todo.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Todo{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
