services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - app-network
    ports:
      - "5173:5173"

networks:
  app-network:
    driver: bridge
